name: morphling
description: "A morphling library from app-way-data."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
    
  ## 
  intl: ^0.19.0

  ## Dependency Injection
  get_it: ^7.2.0

dev_dependencies:
  flutter_test: 
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
