name: core
description: A core package for way-data app
version: 1.0.0+1

publish_to: 'none' 

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Foundation
  morphling:
    path: ../morphling

  # Http
  http: ^0.13.5

  #
  cupertino_icons: ^1.0.8

  # Network cached image
  cached_network_image: ^3.3.0  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

